mqtt:
  host: tcp://pi-master:1883
  username:
  password:
  client-id: io-engine
  topic: io-actions
  action-topic: home/actions
  trigger-topic: home/triggers
  driver-sync-topic: home/driver-sync
sound:
  preset-location: /home/pi/sound-preset
db:
  path: /home/pi/smart-db

