mqtt:
  host: tcp://pi-master:1883
  username:
  password:
  client-id: io-engine
  topic: io-actions
  action-topic: home/actions
  trigger-topic: home/triggers
  hermes-intent-topic: hermes/intent/+
  driver-sync-topic: home/driver-sync
modbus:
  host: 192.168.0.10
sound:
  preset-location: /home/pi/sound-preset
db:
  path: /home/pi/smart-db
spring:
  datasource:
    url: 'jdbc:sqlite:/home/pi/smart-db/smart.db'
    driver-class-name: 'org.sqlite.JDBC'
flyway:
  baseline-on-migrate: true
  #    schemas: myDb
  enabled: true
  url: 'jdbc:sqlite:/home/pi/smart-db/smart.db'
  validate-on-migrate: true
  locations: "classpath:db/migration"